//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPortfolioProject.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbDemoPortfolioEntities : DbContext
    {
        public DbDemoPortfolioEntities()
            : base("name=DbDemoPortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAbout> TBLAbout { get; set; }
        public virtual DbSet<TBLServiceFeature> TBLServiceFeature { get; set; }
        public virtual DbSet<TBLServices> TBLServices { get; set; }
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
        public virtual DbSet<TBLTestomonial> TBLTestomonial { get; set; }
        public virtual DbSet<TBLAcademic> TBLAcademic { get; set; }
        public virtual DbSet<TBLExperience> TBLExperience { get; set; }
        public virtual DbSet<TBLMember> TBLMember { get; set; }
        public virtual DbSet<TBLMessage> TBLMessage { get; set; }
        public virtual DbSet<TBLContact> TBLContact { get; set; }
    }
}
